## Explore Board Representations

In [1]:
import numpy as np

## Ideas
* cribbing this from [pgx](https://github.com/sotetsuk/pgx/blob/main/docs/backgammon.md)
* there are 24 points, you represent pieces by 1 for white and -1 for black
* you add to the point you move to, you subtract to the point you take away
* you evaluate legal moves by checking to see that >= -1 for white, <= 1 for black
* say white goes 0-23, black goes 23-0

In [5]:
board = np.zeros([1,24])

In [6]:
board

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
board.reshape([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
initial_board = np.array([[2., 0., 0., 0., 0., -5.],
                       [0., -3., 0., 0., 0., 5],
                       [-5., 0., 0., 0., 3., 0.],
                       [5., 0., 0., 0., 0., -2.]])

In [13]:
initial_board.reshape([2,2, 6])

array([[[ 2.,  0.,  0.,  0.,  0., -5.],
        [ 0., -3.,  0.,  0.,  0.,  5.]],

       [[-5.,  0.,  0.,  0.,  3.,  0.],
        [ 5.,  0.,  0.,  0.,  0., -2.]]])

In [22]:
def roll():
    return np.random.randint(low=1, high=6, size=2)

In [25]:
roll()

array([1, 3])

In [26]:
def evaluate_legal_moves(board, roll, color):
    list_of_moves = []
    # find indices with checkers
    # find indices with 1 or fewer of opponents checkers
    # find all possible legal moves for each index in first list to second list
    # write these to the 6/5, 8/5 notation we understand (3,1 for first roll)
    return list_of_moves